# Generated by Django 6.0.2 on 2026-02-15 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaborador", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoItemAvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimensao",
                    models.CharField(
                        choices=[
                            ("COMPORTAMENTO", "Comportamento"),
                            ("ENTREGAS", "Entregas"),
                            ("TRABALHO_EM_EQUIPE", "Trabalho em Equipe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo_item_avaliacao_desempenho", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "Tipo de Item de Avaliação de Desempenho",
                "verbose_name_plural": "Tipos de Itens de Avaliação de Desempenho",
                "ordering": ["dimensao", "tipo_item_avaliacao_desempenho"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_competencia", models.DateField()),
                (
                    "status_avaliacao",
                    models.CharField(
                        choices=[
                            ("CRIADA", "Criada"),
                            ("EM_ELABORACAO", "Em Elaboração"),
                            ("EM_AVALIACAO", "Em Avaliação"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="CRIADA",
                        max_length=20,
                    ),
                ),
                ("nota", models.FloatField(default=0.0)),
                ("sugestoes_supervisor", models.TextField(blank=True, null=True)),
                ("observacoes_avaliado", models.TextField(blank=True, null=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="colaborador.colaborador",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisoes",
                        to="colaborador.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Desempenho",
                "verbose_name_plural": "Avaliações de Desempenho",
                "ordering": ["-mes_competencia"],
                "unique_together": {("colaborador", "mes_competencia")},
            },
        ),
        migrations.CreateModel(
            name="ItemAvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="avaliacao.avaliacaodesempenho",
                    ),
                ),
                (
                    "tipo_item_avaliacao_desempenho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos",
                        to="avaliacao.tipoitemavaliacaodesempenho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Avaliação de Desempenho",
                "verbose_name_plural": "Itens de Avaliação de Desempenho",
                "ordering": [
                    "tipo_item_avaliacao_desempenho__dimensao",
                    "tipo_item_avaliacao_desempenho__tipo_item_avaliacao_desempenho",
                ],
            },
        ),
    ]
