# Generated by Django 6.0.2 on 2026-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="itemavaliacaodesempenho",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="itemavaliacaodesempenho",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tipoitemavaliacaodesempenho",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tipoitemavaliacaodesempenho",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
